In [2]:
import pandas as pd

In [3]:
deli= pd.read_csv('C:/Users/Arnab/Desktop/WPL/10-10-2020/deliveries.csv')

In [43]:
match= pd.read_csv('C:/Users/Arnab/Desktop/WPL/10-10-2020/matches.csv')

In [5]:
deli.describe()

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs
count,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000
mean,1802.252957,1.482952,10.162488,3.615587,0.000452,0.036721,0.004936,0.021136,0.004183,0.000056,1.246864,0.067032,1.313897
std,3472.322805,0.502074,5.677684,1.806966,0.021263,0.251161,0.116480,0.194908,0.070492,0.016709,1.608270,0.342553,1.605422
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,190.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,379.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,567.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,11415.000000,5.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,7.000000,7.000000,10.000000

In [93]:
deli.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
dtypes: int64(13), object(8)
memory usage: 28.7+ MB

In [11]:
deli.isna().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [20]:
deli.tail(20)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
179058,11415,2,Chennai Super Kings,Mumbai Indians,17,5,SR Watson,DJ Bravo,JJ Bumrah,0,...,1,0,0,0,1,1,2,NaN,NaN,NaN
179059,11415,2,Chennai Super Kings,Mumbai Indians,17,6,DJ Bravo,SR Watson,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179060,11415,2,Chennai Super Kings,Mumbai Indians,18,1,DJ Bravo,SR Watson,KH Pandya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179061,11415,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179062,11415,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179063,11415,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179064,11415,2,Chennai Super Kings,Mumbai Indians,18,5,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
179065,11415,2,Chennai Super Kings,Mumbai Indians,18,6,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179066,11415,2,Chennai Super Kings,Mumbai Indians,19,1,SR Watson,DJ Bravo,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179067,11415,2,Chennai Super Kings,Mumbai Indians,19,2,DJ Bravo,SR Watson,JJ Bumrah,0,...,0,0,0,0,0,0,0,DJ Bravo,caught,Q de Kock
179068,11415,2,Chennai Super Kings,Mumbai Indians,19,3,RA Jadeja,SR Watson,JJ Bumrah,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179069,11415,2,Chennai Super Kings,Mumbai Indians,19,4,RA Jadeja,SR Watson,JJ Bumrah,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
179070,11415,2,Chennai Super Kings,Mumbai Indians,19,5,RA Jadeja,SR Watson,JJ Bumrah,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179071,11415,2,Chennai Super Kings,Mumbai Indians,19,6,RA Jadeja,SR Watson,JJ Bumrah,0,...,4,0,0,0,4,4,8,NaN,NaN,NaN
179072,11415,2,Chennai Super Kings,Mumbai Indians,20,1,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [18]:
deli['batting_team'].unique()

array(['Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Mumbai Indians', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Daredevils',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [19]:
deli.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [21]:
deli['inning'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [28]:
batting_teams = deli['batting_team'].unique()

In [32]:
batting_teams

array(['Sunrisers Hyderabad', 'Royal Challengers Bangalore',
       'Mumbai Indians', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Daredevils',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [31]:
len(batting_teams)

15

In [37]:
bowling_teams = deli['bowling_team'].unique()
bowling_teams

array(['Royal Challengers Bangalore', 'Sunrisers Hyderabad',
       'Rising Pune Supergiant', 'Mumbai Indians',
       'Kolkata Knight Riders', 'Gujarat Lions', 'Kings XI Punjab',
       'Delhi Daredevils', 'Chennai Super Kings', 'Rajasthan Royals',
       'Deccan Chargers', 'Kochi Tuskers Kerala', 'Pune Warriors',
       'Rising Pune Supergiants', 'Delhi Capitals'], dtype=object)

In [38]:
len(bowling_teams)

15

In [39]:
deli['ball'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

## Rohit Sharma

In [89]:
batsman = deli['batsman'].unique()
len(batsman)
batsman

array(['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuvraj Singh',
       'DJ Hooda', 'BCJ Cutting', 'CH Gayle', 'Mandeep Singh', 'TM Head',
       'KM Jadhav', 'SR Watson', 'Sachin Baby', 'STR Binny', 'S Aravind',
       'YS Chahal', 'TS Mills', 'A Choudhary', 'PA Patel', 'JC Buttler',
       'RG Sharma', 'N Rana', 'AT Rayudu', 'KH Pandya', 'KA Pollard',
       'HH Pandya', 'TG Southee', 'AM Rahane', 'MA Agarwal', 'SPD Smith',
       'BA Stokes', 'MS Dhoni', 'JJ Roy', 'BB McCullum', 'SK Raina',
       'AJ Finch', 'KD Karthik', 'G Gambhir', 'CA Lynn', 'MK Tiwary',
       'DT Christian', 'HM Amla', 'M Vohra', 'WP Saha', 'AR Patel',
       'GJ Maxwell', 'DA Miller', 'Vishnu Vinod', 'Iqbal Abdulla',
       'P Negi', 'AP Tare', 'SW Billings', 'KK Nair', 'SV Samson',
       'RR Pant', 'CH Morris', 'CR Brathwaite', 'PJ Cummins', 'A Mishra',
       'S Nadeem', 'Z Khan', 'DR Smith', 'DS Kulkarni', 'P Kumar',
       'Basil Thampi', 'RV Uthappa', 'MK Pandey', 'YK Pathan', 'SA Yadav',
       'CR Woakes', 'SP Narine', 'Harbhajan Singh', 'AB de Villiers',
       'CJ Anderson', 'F du Plessis', 'RA Tripathi', 'R Bhatia',
       'DL Chahar', 'A Zampa', 'AB Dinda', 'Imran Tahir', 'NV Ojha',
       'V Shankar', 'Rashid Khan', 'B Kumar', 'MP Stoinis', 'MM Sharma',
       'VR Aaron', 'V Kohli', 'MJ McClenaghan', 'Ankit Sharma',
       'SN Thakur', 'RD Chahar', 'LH Ferguson', 'C de Grandhomme',
       'Bipul Sharma', 'SS Iyer', 'EJG Morgan', 'KC Cariappa',
       'Sandeep Sharma', 'Ishan Kishan', 'JD Unadkat', 'AF Milne',
       'S Badree', 'AD Mathews', 'Mohammed Shami', 'Mohammad Nabi',
       'I Sharma', 'RA Jadeja', 'AJ Tye', 'KS Williamson', 'SE Marsh',
       'Shakib Al Hasan', 'JP Faulkner', 'MG Johnson', 'K Rabada',
       'AD Nath', 'NM Coulter-Nile', 'Kuldeep Yadav', 'UT Yadav',
       'Washington Sundar', 'KV Sharma', 'DM Bravo', 'AR Bawne',
       'SP Jackson', 'MJ Guptill', 'Anureet Singh', 'IK Pathan',
       'Ankit Soni', 'JJ Bumrah', 'SL Malinga', 'PJ Sangwan', 'S Kaul',
       'LMP Simmons', 'MN Samuels', 'Swapnil Singh', 'R Tewatia',
       'MM Patel', 'SS Tiwary', 'TA Boult', 'CJ Jordan', 'IR Jaggi',
       'PP Chawla', 'AS Rajpoot', 'SC Ganguly', 'RT Ponting', 'DJ Hussey',
       'Mohammad Hafeez', 'R Dravid', 'W Jaffer', 'JH Kallis', 'CL White',
       'MV Boucher', 'B Akhil', 'AA Noffke', 'SB Joshi', 'ML Hayden',
       'MEK Hussey', 'JDP Oram', 'S Badrinath', 'K Goel', 'JR Hopes',
       'KC Sangakkara', 'SM Katich', 'T Kohli', 'M Kaif', 'DS Lehmann',
       'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'V Sehwag',
       'L Ronchi', 'ST Jayasuriya', 'DJ Thornely', 'PR Shah', 'AM Nayar',
       'SM Pollock', 'S Chanderpaul', 'LRPL Taylor', 'AC Gilchrist',
       'Y Venugopal Rao', 'VVS Laxman', 'A Symonds', 'SB Styris',
       'AS Yadav', 'SB Bangar', 'WPUJC Vaas', 'RP Singh', 'LR Shukla',
       'DPMD Jayawardene', 'S Sohal', 'B Lee', 'WA Mota', 'Kamran Akmal',
       'Shahid Afridi', 'DJ Bravo', 'MA Khote', 'A Nehra', 'GC Smith',
       'Pankaj Singh', 'RR Sarwan', 'S Sreesanth', 'VRV Singh',
       'R Vinay Kumar', 'AB Agarkar', 'M Kartik', 'Shoaib Malik',
       'MF Maharoof', 'VY Mahesh', 'TM Srivastava', 'B Chipli',
       'DW Steyn', 'DB Das', 'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna',
       'SA Asnodkar', 'Sohail Tanvir', 'Salman Butt', 'BJ Hodge',
       'Umar Gul', 'SP Fleming', 'S Vidyut', 'JA Morkel', 'LPC Silva',
       'DB Ravi Teja', 'Misbah-ul-Haq', 'YV Takawale', 'RR Raje',
       'Mohammad Asif', 'GD McGrath', 'Joginder Sharma', 'MS Gony',
       'M Muralitharan', 'M Ntini', 'DT Patil', 'A Kumble', 'S Anirudha',
       'CK Kapugedera', 'A Chopra', 'T Taibu', 'J Arunkumar', 'PP Ojha',
       'SP Goswami', 'SR Tendulkar', 'U Kaul', 'TM Dilshan',
       'AD Mascarenhas', 'Niraj Patel', 'LA Pomersbach', 'Younis Khan',
       'PM Sarvesh Kumar', 'DP Vijaykumar', 'Shoaib Akhtar',
       'Abdur Razzak', 'H Das', 'SD Chitnis', 'CRD Fernando',
       'VS Yeligati', 'L Balaji', 'A Mukund', 'RR Powar', 'JP Duminy',
       'A Flintoff', 'T Thushara', 'JD Ryder', 'KP Pietersen',
       'T Henderson', 'Kamran Khan', 'RS Bopara', 'R Bishnoi',
       'FH Edwards', 'PC Valthaty', 'RJ Quiney', 'AS Raut',
       'Yashpal Singh', 'M Manhas', 'AA Bilakhia', 'AN Ghosh',
       'BAW Mendis', 'DL Vettori', 'MN van Wyk', 'RE van der Merwe',
       'TL Suman', 'Shoaib Ahmed', 'GR Napier', 'KP Appanna',
       'LA Carseldine', 'SM Harwood', 'M Vijay', 'SB Jakati', 'RJ Harris',
       'D du Preez', 'M Morkel', 'J Botha', 'C Nanda', 'Mashrafe Mortaza',
       'A Singh', 'GJ Bailey', 'AB McDonald', 'Y Nagar', 'SS Shaikh',
       'R Ashwin', 'Mohammad Ashraful', 'CA Pujara', 'OA Shah',
       'Anirudh Singh', 'Jaskaran Singh', 'R Sathish', 'R McLaren',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'MS Bisla', 'YA Abdulla',
       'JM Kemp', 'S Tyagi', 'RS Gavaskar', 'SE Bond', 'S Ladda',
       'DP Nannes', 'MJ Lumb', 'DR Martyn', 'S Narwal', 'AB Barath',
       'FY Fazal', 'AC Voges', 'MD Mishra', 'J Theron', 'SJ Srivastava',
       'R Sharma', 'SW Tait', 'KB Arun Karthik', 'KAJ Roach',
       'PD Collingwood', 'CK Langeveldt', 'VS Malik', 'A Mithun',
       'AP Dole', 'AN Ahmed', 'RS Sodhi', 'DE Bollinger', 'S Sriram',
       'B Sumanth', 'C Madan', 'AG Paunikar', 'MR Marsh', 'Harmeet Singh',
       'RV Gomez', 'AUK Pathan', 'UBT Chand', 'DJ Jacobs', 'Sunny Singh',
       'NJ Rimmington', 'AL Menaria', 'WD Parnell', 'JJ van der Wath',
       'R Ninan', 'MS Wade', 'TD Paine', 'SB Wagh', 'AC Thomas',
       'JEC Franklin', 'DH Yagnik', 'S Randiv', 'BJ Haddin',
       'NLTC Perera', 'NL McCullum', 'JE Taylor', 'J Syed Mohammad',
       'RN ten Doeschate', 'TR Birt', 'AG Murtaza', 'Harpreet Singh',
       'M Klinger', 'AC Blizzard', 'I Malhotra', 'L Ablish', 'CA Ingram',
       'P Parameswaran', 'CJ Ferguson', 'AA Chavan', 'ND Doshi',
       'Y Gnaneswara Rao', 'S Rana', 'BA Bhatt', 'RE Levi', 'KK Cooper',
       'HV Patel', 'DAJ Bracewell', 'DJ Harris', 'GB Hogg', 'RR Bhatkal',
       'CJ McKay', 'N Saini', 'Azhar Mahmood', 'RJ Peterson',
       'KMDN Kulasekara', 'A Ashish Reddy', 'V Pratap Singh',
       'BB Samantray', 'MJ Clarke', 'Gurkeerat Singh', 'AP Majumdar',
       'PA Reddy', 'K Upadhyay', 'P Awana', 'AD Russell', 'A Chandila',
       'Sunny Gupta', 'MC Juneja', 'GH Vihari', 'MDKJ Perera', 'R Shukla',
       'B Laughlin', 'BMAJ Mendis', 'R Rampaul', 'SMSM Senanayake',
       'BJ Rohrer', 'KL Rahul', 'Q de Kock', 'R Dhawan', 'LJ Wright',
       'IC Pandey', 'CM Gautam', 'X Thalaivan Sargunam', 'DJG Sammy',
       'KW Richardson', 'UA Birla', 'Parvez Rasool', 'PV Tambe',
       'NJ Maddinson', 'JDS Neesham', 'MA Starc', 'BR Dunk', 'RR Rossouw',
       'Shivam Sharma', 'VH Zol', 'BE Hendricks', 'S Gopal', 'M de Lange',
       'JO Holder', 'Karanveer Singh', 'SA Abbott', 'J Suchith',
       'RG More', 'D Wiese', 'SN Khan', 'DJ Muthuswami', 'C Munro',
       'P Sahu', 'KJ Abbott', 'M Ashwin', 'NS Naik', 'PSP Handscomb',
       'J Yadav', 'UT Khawaja', 'F Behardien', 'BB Sran', 'S Kaushik',
       'ER Dwivedi', 'E Lewis', 'M Wood', 'R Singh', 'D Short',
       'K Gowtham', 'T Curran', 'M Markande', 'B Stanlake', 'M Ur Rahman',
       'A Dananjaya', 'S Gill', 'S Mavi', 'Mohammed Siraj', 'H Klaasen',
       'R Bhui', 'J Archer', 'P Shaw', 'L Plunkett', 'Mustafizur Rahman',
       'A Hales', 'M Lomror', 'D Shorey', 'M Ali', 'P Krishna',
       'P Chopra', 'J Searles', 'I Sodhi', 'S Hetmyer', 'S Dube',
       'J Bairstow', 'C Ingram', 'K Paul', 'R Salam', 'N Pooran',
       'N Naik', 'H Vihari', 'P R Barman', 'S Curran', 'H Viljoen',
       'Avesh Khan', 'S Lamichhane', 'S Sharma', 'H Gurney', 'SD Lad',
       'A Joseph', 'R Parag', 'M Santner', 'J Denly', 'L Livingstone',
       'K Ahmed', 'A Turner', 'H Brar', 'S Rutherford', 'P Raj',
       'S Singh'], dtype=object)

In [91]:
rohit = deli[deli['batsman'] == 'RG Sharma']

In [94]:
rohit

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
275,2,1,Mumbai Indians,Rising Pune Supergiant,5,3,RG Sharma,JC Buttler,Imran Tahir,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
276,2,1,Mumbai Indians,Rising Pune Supergiant,5,4,RG Sharma,JC Buttler,Imran Tahir,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
278,2,1,Mumbai Indians,Rising Pune Supergiant,5,6,RG Sharma,JC Buttler,Imran Tahir,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
279,2,1,Mumbai Indians,Rising Pune Supergiant,6,1,RG Sharma,JC Buttler,DL Chahar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
285,2,1,Mumbai Indians,Rising Pune Supergiant,7,1,RG Sharma,JC Buttler,Imran Tahir,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178853,11415,1,Mumbai Indians,Chennai Super Kings,4,5,RG Sharma,Q de Kock,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
178854,11415,1,Mumbai Indians,Chennai Super Kings,4,6,RG Sharma,Q de Kock,Harbhajan Singh,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
178856,11415,1,Mumbai Indians,Chennai Super Kings,5,2,RG Sharma,Q de Kock,SN Thakur,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178862,11415,1,Mumbai Indians,Chennai Super Kings,6,1,RG Sharma,AS Yadav,DL Chahar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
178863,11415,1,Mumbai Indians,Chennai Super Kings,6,2,RG Sharma,AS Yadav,DL Chahar,0,...,0,0,0,0,0,0,0,RG Sharma,caught,MS Dhoni

In [102]:
total_rohit_match = len(rohit['match_id'].unique())
total_rohit_match

182

In [103]:
total_rohit_score = rohit['batsman_runs'].sum()
total_rohit_score

4914

In [104]:
## average of rohits score
total_rohit_score/total_rohit_match

27.0

## Kagiso Rabada

In [105]:
bowler = deli['bowler'].unique()
len(bowler)
bowler

array(['TS Mills', 'A Choudhary', 'YS Chahal', 'S Aravind', 'SR Watson',
       'TM Head', 'STR Binny', 'A Nehra', 'B Kumar', 'BCJ Cutting',
       'Rashid Khan', 'DJ Hooda', 'MC Henriques', 'Bipul Sharma',
       'AB Dinda', 'DL Chahar', 'BA Stokes', 'Imran Tahir', 'A Zampa',
       'R Bhatia', 'TG Southee', 'HH Pandya', 'MJ McClenaghan',
       'JJ Bumrah', 'KH Pandya', 'KA Pollard', 'TA Boult', 'PP Chawla',
       'SP Narine', 'CR Woakes', 'Kuldeep Yadav', 'YK Pathan', 'P Kumar',
       'DS Kulkarni', 'MS Gony', 'S Kaushik', 'DR Smith', 'SB Jakati',
       'Sandeep Sharma', 'MM Sharma', 'AR Patel', 'T Natarajan',
       'MP Stoinis', 'Swapnil Singh', 'DT Christian', 'RD Chahar',
       'Z Khan', 'CH Morris', 'PJ Cummins', 'S Nadeem', 'A Mishra',
       'CR Brathwaite', 'B Stanlake', 'Iqbal Abdulla', 'P Negi',
       'SK Raina', 'Tejas Baroka', 'Basil Thampi', 'SL Malinga',
       'Harbhajan Singh', 'AS Rajpoot', 'VR Aaron', 'CJ Anderson',
       'Mustafizur Rahman', 'UT Yadav', 'C de Grandhomme', 'I Sharma',
       'GJ Maxwell', 'S Badree', 'AJ Tye', 'RA Jadeja', 'Ankit Sharma',
       'LH Ferguson', 'SN Thakur', 'KC Cariappa', 'MM Patel', 'AF Milne',
       'JD Unadkat', 'NM Coulter-Nile', 'Mohammed Shami', 'AD Mathews',
       'BB Sran', 'S Kaul', 'Mohammad Nabi', 'J Yadav', 'Mohammed Siraj',
       'Yuvraj Singh', 'JP Faulkner', 'Shakib Al Hasan', 'K Rabada',
       'MG Johnson', 'Washington Sundar', 'SS Agarwal', 'NB Singh',
       'KV Sharma', 'RA Tripathi', 'Ankit Soni', 'Anureet Singh',
       'IK Pathan', 'PJ Sangwan', 'MN Samuels', 'MJ Henry', 'R Tewatia',
       'R Vinay Kumar', 'Avesh Khan', 'HV Patel', 'CJ Jordan',
       'AA Noffke', 'JH Kallis', 'SB Joshi', 'CL White', 'AB Agarkar',
       'SC Ganguly', 'LR Shukla', 'B Lee', 'S Sreesanth', 'JR Hopes',
       'K Goel', 'WA Mota', 'JDP Oram', 'M Muralitharan', 'P Amarnath',
       'Joginder Sharma', 'GD McGrath', 'B Geeves', 'MF Maharoof',
       'DL Vettori', 'SK Trivedi', 'SK Warne', 'D Salunkhe', 'B Akhil',
       'SM Pollock', 'ST Jayasuriya', 'AM Nayar', 'M Kartik',
       'Mohammad Hafeez', 'DJ Hussey', 'WPUJC Vaas', 'RP Singh',
       'SB Styris', 'SB Bangar', 'A Symonds', 'PP Ojha', 'Pankaj Singh',
       'Mohammad Asif', 'VY Mahesh', 'Shahid Afridi', 'DJ Bravo',
       'VS Yeligati', 'MA Khote', 'D Kalyankrishna', 'VRV Singh',
       'Sohail Tanvir', 'A Kumble', 'DNT Zoysa', 'SD Chitnis',
       'Shoaib Malik', 'DW Steyn', 'JA Morkel', 'CRD Fernando', 'V Kohli',
       'V Sehwag', 'Gagandeep Singh', 'Y Venugopal Rao', 'Umar Gul',
       'M Ntini', 'DP Vijaykumar', 'DB Ravi Teja', 'LPC Silva',
       'DJ Thornely', 'RR Raje', 'S Vidyut', 'L Balaji', 'CK Kapugedera',
       'AD Mascarenhas', 'Shoaib Akhtar', 'RR Powar', 'PM Sarvesh Kumar',
       'Abdur Razzak', 'TM Dilshan', 'RG Sharma', 'A Nel', 'BAW Mendis',
       'T Thushara', 'A Flintoff', 'Kamran Khan', 'T Henderson',
       'JD Ryder', 'DP Nannes', 'AM Salvi', 'YA Abdulla', 'VS Malik',
       'FH Edwards', 'Harmeet Singh', 'CH Gayle', 'KP Pietersen',
       'LRPL Taylor', 'RS Bopara', 'MK Tiwary', 'RR Bose', 'KP Appanna',
       'Shoaib Ahmed', 'BJ Hodge', 'SR Tendulkar', 'RE van der Merwe',
       'JP Duminy', 'S Tyagi', 'GR Napier', 'SM Harwood', 'AS Raut',
       'D du Preez', 'RJ Harris', 'TL Suman', 'A Singh', 'M Morkel',
       'LA Carseldine', 'A Mithun', 'C Nanda', 'SS Sarkar', 'AM Rahane',
       'J Botha', 'Mashrafe Mortaza', 'AB McDonald', 'Y Nagar',
       'CK Langeveldt', 'R Ashwin', 'RA Shaikh', 'Jaskaran Singh',
       'SW Tait', 'A Uniyal', 'AA Jhunjhunwala', 'R McLaren',
       'AG Murtaza', 'R Sathish', 'RS Gavaskar', 'JM Kemp', 'S Ladda',
       'SE Bond', 'S Narwal', 'SJ Srivastava', 'AC Voges', 'R Sharma',
       'J Theron', 'NLTC Perera', 'KAJ Roach', 'PD Collingwood',
       'C Ganapathy', 'MB Parmar', 'SB Wagh', 'DE Bollinger', 'AP Dole',
       'AN Ahmed', 'FY Fazal', 'MR Marsh', 'L Ablish', 'S Sriram',
       'AJ Finch', 'ND Doshi', 'S Randiv', 'AL Menaria', 'AUK Pathan',
       'RV Gomez', 'JEC Franklin', 'AC Thomas', 'WD Parnell', 'M Manhas',
       'NJ Rimmington', 'RN ten Doeschate', 'BA Bhatt', 'JJ van der Wath',
       'R Ninan', 'PC Valthaty', 'S Dhawan', 'J Syed Mohammad',
       'NL McCullum', 'JE Taylor', 'KMDN Kulasekara', 'P Parameswaran',
       'I Malhotra', 'B Chipli', 'AA Kazi', 'Anand Rajan', 'P Prasanth',
       'Y Gnaneswara Rao', 'AA Chavan', 'S Rana', 'SS Mundhe', 'RW Price',
       'M de Lange', 'KK Cooper', 'DAJ Bracewell', 'DJ Harris',
       'TP Sudhindra', 'F du Plessis', 'GB Hogg', 'RR Bhatkal', 'P Awana',
       'V Pratap Singh', 'CJ McKay', 'AD Russell', 'A Ashish Reddy',
       'Azhar Mahmood', 'A Chandila', 'LJ Wright', 'RJ Peterson',
       'R Shukla', 'MJ Clarke', 'BW Hilfenhaus', 'SPD Smith',
       'K Upadhyay', 'Sunny Gupta', 'B Laughlin', 'GH Vihari',
       'BMAJ Mendis', 'Harmeet Singh (2)', 'R Dhawan', 'R Rampaul',
       'SMSM Senanayake', 'JO Holder', 'IC Pandey', 'DJG Sammy',
       'KW Richardson', 'P Suyal', 'PV Tambe', 'BJ Rohrer',
       'Parvez Rasool', 'MG Neser', 'AC Gilchrist', 'MA Starc',
       'JDS Neesham', 'M Vijay', 'SA Yadav', 'Shivam Sharma', 'V Shankar',
       'LMP Simmons', 'K Santokie', 'S Gopal', 'BE Hendricks',
       'JW Hastings', 'Karanveer Singh', 'DJ Muthuswami', 'SA Abbott',
       'J Suchith', 'RG More', 'D Wiese', 'GS Sandhu', 'Gurkeerat Singh',
       'M Ashwin', 'C Munro', 'P Sahu', 'KJ Abbott', 'T Shamsi',
       'SM Boland', 'Sachin Baby', 'N Rana', 'KS Williamson', 'M Wood',
       'M Markande', 'M Ur Rahman', 'K Khejroliya', 'K Gowtham',
       'D Short', 'T Curran', 'A Dananjaya', 'S Mavi', 'J Archer',
       'L Plunkett', 'I Sodhi', 'M Lomror', 'L Ngidi', 'KM Asif',
       'D Willey', 'P Krishna', 'M Ali', 'J Searles', 'S Lamichhane',
       'J Dala', 'K Ahmed', 'N Saini', 'S Dube', 'L Ferguson', 'S Sharma',
       'R Salam', 'K Paul', 'S Curran', 'V Chakravarthy', 'H Viljoen',
       'Mandeep Singh', 'P R Barman', 'M Santner', 'H Vihari',
       'J Behrendorff', 'S Kuggeleijn', 'A Joseph', 'H Gurney',
       'S Midhun', 'R Parag', 'L Livingstone', 'SN Khan', 'S Rutherford',
       'H Brar', 'P Raj', 'O Thomas', 'A Roy', 'S Warrier'], dtype=object)

In [107]:
rabada = deli[deli['bowler'] == 'K Rabada']
rabada

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
5512,24,1,Mumbai Indians,Delhi Daredevils,1,1,PA Patel,JC Buttler,K Rabada,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
5513,24,1,Mumbai Indians,Delhi Daredevils,1,2,JC Buttler,PA Patel,K Rabada,0,...,0,0,0,0,0,5,5,NaN,NaN,NaN
5514,24,1,Mumbai Indians,Delhi Daredevils,1,3,JC Buttler,PA Patel,K Rabada,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
5515,24,1,Mumbai Indians,Delhi Daredevils,1,4,PA Patel,JC Buttler,K Rabada,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
5516,24,1,Mumbai Indians,Delhi Daredevils,1,5,JC Buttler,PA Patel,K Rabada,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175903,11337,2,Royal Challengers Bangalore,Delhi Capitals,20,3,Washington Sundar,MP Stoinis,K Rabada,0,...,0,0,0,0,0,0,0,Washington Sundar,caught,SS Iyer
175904,11337,2,Royal Challengers Bangalore,Delhi Capitals,20,4,MP Stoinis,UT Yadav,K Rabada,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
175905,11337,2,Royal Challengers Bangalore,Delhi Capitals,20,5,MP Stoinis,UT Yadav,K Rabada,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
175906,11337,2,Royal Challengers Bangalore,Delhi Capitals,20,6,MP Stoinis,UT Yadav,K Rabada,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
175907,11337,2,Royal Challengers Bangalore,Delhi Capitals,20,7,MP Stoinis,UT Yadav,K Rabada,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [129]:
#Total rabada match
total_rabada_match = len(rabada['match_id'].unique())
total_rabada_match

18

In [109]:
rabada['dismissal_kind'].unique()

array([nan, 'bowled', 'run out', 'caught'], dtype=object)

In [131]:
rabada_bowled = rabada[(rabada['dismissal_kind'] == 'bowled')]
rabada_bowled

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
5539,24,1,Mumbai Indians,Delhi Daredevils,4,7,PA Patel,JC Buttler,K Rabada,0,...,0,0,0,0,0,0,0,PA Patel,bowled,NaN
7262,31,2,Kolkata Knight Riders,Delhi Daredevils,2,2,SP Narine,G Gambhir,K Rabada,0,...,0,0,0,0,0,0,0,SP Narine,bowled,NaN
7343,31,2,Kolkata Knight Riders,Delhi Daredevils,15,5,MK Pandey,G Gambhir,K Rabada,0,...,0,0,0,0,0,0,0,MK Pandey,bowled,NaN
172040,11321,2,Sunrisers Hyderabad,Delhi Capitals,19,6,K Ahmed,S Sharma,K Rabada,0,...,0,0,0,0,0,0,0,K Ahmed,bowled,NaN
174329,11331,1,Rajasthan Royals,Delhi Capitals,20,4,STR Binny,AM Rahane,K Rabada,0,...,0,0,0,0,0,0,0,STR Binny,bowled,NaN
174332,11331,1,Rajasthan Royals,Delhi Capitals,20,7,R Parag,AM Rahane,K Rabada,0,...,0,0,0,0,0,0,0,R Parag,bowled,NaN

In [128]:
rabada_caught = rabada[(rabada['dismissal_kind'] == 'caught')]
rabada_caught

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
9482,41,1,Gujarat Lions,Delhi Daredevils,2,1,BB McCullum,DR Smith,K Rabada,0,...,0,0,0,0,0,0,0,BB McCullum,caught,RR Pant
9589,41,1,Gujarat Lions,Delhi Daredevils,19,3,AJ Finch,RA Jadeja,K Rabada,0,...,0,0,0,0,0,0,0,AJ Finch,caught,RR Pant
10290,44,1,Mumbai Indians,Delhi Daredevils,16,3,RG Sharma,KA Pollard,K Rabada,0,...,0,0,0,0,0,0,0,RG Sharma,caught,A Mishra
165433,11139,2,Mumbai Indians,Delhi Capitals,17,3,BCJ Cutting,Yuvraj Singh,K Rabada,0,...,0,0,0,0,0,0,0,BCJ Cutting,caught,RR Pant
165446,11139,2,Mumbai Indians,Delhi Capitals,19,3,Yuvraj Singh,MJ McClenaghan,K Rabada,0,...,0,0,0,0,0,0,0,Yuvraj Singh,caught,R Tewatia
165948,11141,2,Chennai Super Kings,Delhi Capitals,20,1,KM Jadhav,MS Dhoni,K Rabada,0,...,0,0,0,0,0,0,0,KM Jadhav,caught,RR Pant
166978,11146,1,Kolkata Knight Riders,Delhi Capitals,7,5,CA Lynn,N Rana,K Rabada,0,...,0,0,0,0,0,0,0,CA Lynn,caught,RR Pant
167797,11149,1,Kings XI Punjab,Delhi Capitals,18,3,H Viljoen,Mandeep Singh,K Rabada,0,...,0,0,0,0,0,0,0,H Viljoen,caught,CH Morris
167807,11149,1,Kings XI Punjab,Delhi Capitals,20,1,M Ashwin,Mandeep Singh,K Rabada,0,...,0,0,0,0,0,0,0,M Ashwin,caught,Avesh Khan
168604,11152,2,Sunrisers Hyderabad,Delhi Capitals,8,6,DA Warner,V Shankar,K Rabada,0,...,0,0,0,0,0,0,0,DA Warner,caught,CH Morris
169436,11311,1,Royal Challengers Bangalore,Delhi Capitals,6,7,AB de Villiers,V Kohli,K Rabada,0,...,0,0,0,0,0,0,0,AB de Villiers,caught,C Ingram
169504,11311,1,Royal Challengers Bangalore,Delhi Capitals,18,1,V Kohli,AD Nath,K Rabada,0,...,0,0,0,0,0,0,0,V Kohli,caught,SS Iyer
169506,11311,1,Royal Challengers Bangalore,Delhi Capitals,18,3,AD Nath,P Negi,K Rabada,0,...,0,0,0,0,0,0,0,AD Nath,caught,RR Pant
169509,11311,1,Royal Challengers Bangalore,Delhi Capitals,18,6,P Negi,TG Southee,K Rabada,0,...,0,0,0,0,0,0,0,P Negi,caught,RR Pant
170882,11317,1,Kolkata Knight Riders,Delhi Capitals,9,4,RV Uthappa,S Gill,K Rabada,0,...,0,0,0,0,0,0,0,RV Uthappa,caught,RR Pant
170924,11317,1,Kolkata Knight Riders,Delhi Capitals,16,1,KD Karthik,AD Russell,K Rabada,0,...,0,0,0,0,0,0,0,KD Karthik,caught,S Dhawan
172024,11321,2,Sunrisers Hyderabad,Delhi Capitals,17,2,DA Warner,V Shankar,K Rabada,0,...,0,0,0,0,0,0,0,DA Warner,caught,SS Iyer
172025,11321,2,Sunrisers Hyderabad,Delhi Capitals,17,3,V Shankar,DJ Hooda,K Rabada,0,...,0,0,0,0,0,0,0,V Shankar,caught,RR Pant
172039,11321,2,Sunrisers Hyderabad,Delhi Capitals,19,5,B Kumar,S Sharma,K Rabada,0,...,0,0,0,0,0,0,0,B Kumar,caught,K Rabada
172849,11325,1,Mumbai Indians,Delhi Capitals,16,1,AS Yadav,KH Pandya,K Rabada,0,...,0,0,0,0,0,0,0,AS Yadav,caught,RR Pant
172877,11325,1,Mumbai Indians,Delhi Capitals,20,4,HH Pandya,KH Pandya,K Rabada,0,...,0,0,0,0,0,0,0,HH Pandya,caught,RR Pant
173526,11328,1,Kings XI Punjab,Delhi Capitals,5,5,MA Agarwal,CH Gayle,K Rabada,0,...,0,0,0,0,0,0,0,MA Agarwal,caught,S Rutherford
173614,11328,1,Kings XI Punjab,Delhi Capitals,20,1,R Ashwin,H Brar,K Rabada,0,...,0,0,0,0,0,0,0,R Ashwin,caught,SS Iyer
175820,11337,2,Royal Challengers Bangalore,Delhi Capitals,6,5,PA Patel,V Kohli,K Rabada,0,...,0,0,0,0,0,0,0,PA Patel,caught,AR Patel
175903,11337,2,Royal Challengers Bangalore,Delhi Capitals,20,3,Washington Sundar,MP Stoinis,K Rabada,0,...,0,0,0,0,0,0,0,Washington Sundar,caught,SS Iyer

In [133]:
## Total wicket = rabada_bowled + rabada_caught
total_wic = 25+6
total_wic

31

In [134]:
## total match
total_rabada_match

18

In [135]:
## average wicket per match 
total_wic/total_rabada_match

1.7222222222222223

In [125]:
match.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [48]:
match.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [49]:
match.sort_values('season', ascending=False)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong
725,11321,2019,Hyderabad,14/04/19,Delhi Capitals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Delhi Capitals,39,0,K Paul,Rajiv Gandhi Intl. Cricket Stadium,Anil Chaudhary,Bruce Oxenford,Chris Gaffaney
723,11319,2019,Mohali,13/04/19,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,8,AB de Villiers,IS Bindra Stadium,S Ravi,Ulhas Gandhe,Nigel Llong
722,11318,2019,Mumbai,13/04/19,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,4,JC Buttler,Wankhede Stadium,Nitin Menon,Nanda Kishore,Marais Erasmus
721,11317,2019,Kolkata,12/04/19,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,7,S Dhawan,Eden Gardens,Yeshwant Barde,O Nandan,Rod Tucker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,86,2008,Mumbai,2008-05-07,Rajasthan Royals,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,7,A Nehra,Dr DY Patil Sports Academy,DJ Harper,RE Koertzen,NaN
86,87,2008,Delhi,2008-05-08,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,4,MS Dhoni,Feroz Shah Kotla,Aleem Dar,RB Tiffin,NaN
87,88,2008,Kolkata,2008-05-08,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,5,0,SC Ganguly,Eden Gardens,Asad Rauf,IL Howell,NaN
88,89,2008,Jaipur,2008-05-09,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,8,YK Pathan,Sawai Mansingh Stadium,MR Benson,AM Saheba,NaN
72,73,2008,Chandigarh,2008-04-27,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,normal,0,Kings XI Punjab,0,4,SM Katich,"Punjab Cricket Association Stadium, Mohali",RE Koertzen,I Shivram,NaN

In [ ]:
match['city'].unique()

## Who will win?

In [137]:
match[(match['team1'] == 'Mumbai Indians')&(match['team2'] == 'Delhi Capitals')]
## mumbai won

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
729,11325,2019,Delhi,18/04/19,Mumbai Indians,Delhi Capitals,Mumbai Indians,bat,normal,0,Mumbai Indians,40,0,HH Pandya,Feroz Shah Kotla Ground,Nigel Llong,Bruce Oxenford,Anil Chaudhary

In [139]:
match[(match['team2'] == 'Mumbai Indians')&(match['team1'] == 'Delhi Capitals')]
## Delhi capitals won

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
698,11139,2019,Mumbai,24/03/19,Delhi Capitals,Mumbai Indians,Mumbai Indians,field,normal,0,Delhi Capitals,37,0,RR Pant,Wankhede Stadium,S Ravi,Yeshwant Barde,O Nandan

In [145]:
total_match = match[(match['team1'] == 'Mumbai Indians')&(match['team2'] == 'Delhi Daredevils')|(match['team1'] == 'Delhi Daredevils')&(match['team2'] == 'Mumbai Indians')]
total_match

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
23,24,2017,Mumbai,2017-04-22,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,14,0,MJ McClenaghan,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
43,44,2017,Delhi,2017-05-06,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,146,0,LMP Simmons,Feroz Shah Kotla,Nitin Menon,CK Nandan,NaN
81,82,2008,Mumbai,2008-05-04,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,29,0,SM Pollock,Dr DY Patil Sports Academy,IL Howell,RE Koertzen,NaN
108,109,2008,Delhi,2008-05-24,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,5,KD Karthik,Feroz Shah Kotla,BF Bowden,K Hariharan,NaN
149,150,2009,East London,2009-05-08,Mumbai Indians,Delhi Daredevils,Mumbai Indians,bat,normal,0,Delhi Daredevils,0,7,A Nehra,Buffalo Park,M Erasmus,SK Tarapore,NaN
169,170,2009,Centurion,2009-05-21,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,4,V Sehwag,SuperSport Park,IL Howell,S Ravi,NaN
182,183,2010,Delhi,2010-03-17,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,98,0,SR Tendulkar,Feroz Shah Kotla,BR Doctrove,SK Tarapore,NaN
220,221,2010,Mumbai,2010-04-13,Mumbai Indians,Delhi Daredevils,Mumbai Indians,bat,normal,0,Mumbai Indians,39,0,KA Pollard,Brabourne Stadium,S Asnani,DJ Harper,NaN
237,238,2011,Delhi,2011-04-10,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,bat,normal,0,Mumbai Indians,0,8,SL Malinga,Feroz Shah Kotla,AM Saheba,RB Tiffin,NaN
281,282,2011,Mumbai,2011-05-07,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,32,0,AT Rayudu,Wankhede Stadium,K Hariharan,SJA Taufel,NaN
326,327,2012,Mumbai,2012-04-16,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,7,S Nadeem,Wankhede Stadium,BF Bowden,SK Tarapore,NaN
341,342,2012,Delhi,2012-04-27,Delhi Daredevils,Mumbai Indians,Mumbai Indians,field,normal,0,Delhi Daredevils,37,0,V Sehwag,Feroz Shah Kotla,Aleem Dar,BNJ Oxenford,NaN
389,390,2013,Mumbai,2013-04-09,Mumbai Indians,Delhi Daredevils,Mumbai Indians,bat,normal,0,Mumbai Indians,44,0,KD Karthik,Wankhede Stadium,M Erasmus,VA Kulkarni,NaN
407,408,2013,Delhi,2013-04-21,Mumbai Indians,Delhi Daredevils,Mumbai Indians,bat,normal,0,Delhi Daredevils,0,9,V Sehwag,Feroz Shah Kotla,HDPK Dharmasena,S Ravi,NaN
472,473,2014,Sharjah,2014-04-27,Mumbai Indians,Delhi Daredevils,Mumbai Indians,bat,normal,0,Delhi Daredevils,0,6,M Vijay,Sharjah Cricket Stadium,Aleem Dar,VA Kulkarni,NaN
507,508,2014,Mumbai,2014-05-23,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,15,0,MEK Hussey,Wankhede Stadium,S Ravi,RJ Tucker,NaN
538,539,2015,Delhi,2015-04-23,Delhi Daredevils,Mumbai Indians,Mumbai Indians,field,normal,0,Delhi Daredevils,37,0,SS Iyer,Feroz Shah Kotla,SD Fry,CK Nandan,NaN
555,556,2015,Mumbai,2015-05-05,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,bat,normal,0,Mumbai Indians,0,5,Harbhajan Singh,Wankhede Stadium,HDPK Dharmasena,CB Gaffaney,NaN
592,593,2016,Delhi,2016-04-23,Delhi Daredevils,Mumbai Indians,Mumbai Indians,field,normal,0,Delhi Daredevils,10,0,SV Samson,Feroz Shah Kotla,S Ravi,C Shamshuddin,NaN
622,623,2016,Visakhapatnam,2016-05-15,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,80,0,KH Pandya,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Nitin Menon,CK Nandan,NaN
644,7902,2018,Mumbai,14/04/18,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,7,JJ Roy,Wankhede Stadium,K Ananthapadmanabhan,Nitin Menon,Rod Tucker
690,7948,2018,Delhi,20/05/18,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,bat,normal,0,Delhi Daredevils,11,0,A Mishra,Feroz Shah Kotla,Kumar Dharmasena,O Nandan,Vineet Kulkarni

In [152]:
total_match.count()

id                 22
season             22
city               22
date               22
team1              22
team2              22
toss_winner        22
toss_decision      22
result             22
dl_applied         22
winner             22
win_by_runs        22
win_by_wickets     22
player_of_match    22
venue              22
umpire1            22
umpire2            22
umpire3             2
dtype: int64

In [150]:
total_match [total_match['winner']=='Mumbai Indians'].count()

id                 11
season             11
city               11
date               11
team1              11
team2              11
toss_winner        11
toss_decision      11
result             11
dl_applied         11
winner             11
win_by_runs        11
win_by_wickets     11
player_of_match    11
venue              11
umpire1            11
umpire2            11
umpire3             0
dtype: int64

## What will the toss winning captain decide to do first?

In [50]:
## Today's match will be between MI and DC
## Sheikh Zayed Stadium

In [64]:
match['city'].unique()

array(['Hyderabad', 'Pune', 'Rajkot', 'Indore', 'Bangalore', 'Mumbai',
       'Kolkata', 'Delhi', 'Chandigarh', 'Kanpur', 'Jaipur', 'Chennai',
       'Cape Town', 'Port Elizabeth', 'Durban', 'Centurion',
       'East London', 'Johannesburg', 'Kimberley', 'Bloemfontein',
       'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala', 'Kochi',
       'Visakhapatnam', 'Raipur', 'Ranchi', 'Abu Dhabi', 'Sharjah', nan,
       'Mohali', 'Bengaluru'], dtype=object)

In [79]:
## Abu dhabi has more number of batting 
match[match['city'] =='Abu Dhabi']

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
457,458,2014,Abu Dhabi,2014-04-16,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,41,0,JH Kallis,Sheikh Zayed Stadium,M Erasmus,RK Illingworth,NaN
459,460,2014,Abu Dhabi,2014-04-18,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Sheikh Zayed Stadium,RK Illingworth,C Shamshuddin,NaN
460,461,2014,Abu Dhabi,2014-04-18,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,4,AM Rahane,Sheikh Zayed Stadium,BF Bowden,RK Illingworth,NaN
464,465,2014,Abu Dhabi,2014-04-21,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,normal,0,Chennai Super Kings,93,0,SK Raina,Sheikh Zayed Stadium,RK Illingworth,C Shamshuddin,NaN
470,471,2014,Abu Dhabi,2014-04-26,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,6,PV Tambe,Sheikh Zayed Stadium,HDPK Dharmasena,C Shamshuddin,NaN
471,472,2014,Abu Dhabi,2014-04-26,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kings XI Punjab,23,0,Sandeep Sharma,Sheikh Zayed Stadium,HDPK Dharmasena,RK Illingworth,NaN
475,476,2014,Abu Dhabi,2014-04-29,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,tie,0,Rajasthan Royals,0,0,JP Faulkner,Sheikh Zayed Stadium,Aleem Dar,AK Chaudhary,NaN

In [65]:
match['team1'].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [66]:
match['team2'].unique()

array(['Royal Challengers Bangalore', 'Rising Pune Supergiant',
       'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Daredevils',
       'Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rajasthan Royals', 'Chennai Super Kings', 'Deccan Chargers',
       'Pune Warriors', 'Kochi Tuskers Kerala', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [75]:
match2 = match.copy()

In [78]:
match2[match2.team1 == 'Delhi Daredevils']

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
14,15,2017,Delhi,2017-04-15,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,normal,0,Delhi Daredevils,51,0,CJ Anderson,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN
17,18,2017,Delhi,2017-04-17,Delhi Daredevils,Kolkata Knight Riders,Delhi Daredevils,bat,normal,0,Kolkata Knight Riders,0,4,NM Coulter-Nile,Feroz Shah Kotla,Nitin Menon,CK Nandan,NaN
30,31,2017,Kolkata,2017-04-28,Delhi Daredevils,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,G Gambhir,Eden Gardens,NJ Llong,S Ravi,NaN
34,35,2017,Chandigarh,2017-04-30,Delhi Daredevils,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,10,Sandeep Sharma,"Punjab Cricket Association IS Bindra Stadium, ...",YC Barde,CK Nandan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,7929,2018,Hyderabad,05/05/18,Delhi Daredevils,Sunrisers Hyderabad,Delhi Daredevils,bat,normal,0,Sunrisers Hyderabad,0,7,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",Bruce Oxenford,O Nandan,Virender Kumar Sharma
677,7935,2018,Delhi,10/05/18,Delhi Daredevils,Sunrisers Hyderabad,Delhi Daredevils,bat,normal,0,Sunrisers Hyderabad,0,9,S Dhawan,Feroz Shah Kotla,C Shamshuddin,Anil Dandekar,S Ravi
680,7938,2018,Delhi,12/05/18,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,5,AB de Villiers,Feroz Shah Kotla,Kumar Dharmasena,Anil Chaudhary,K Ananthapadmanabhan
687,7945,2018,Delhi,18/05/18,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings,field,normal,0,Delhi Daredevils,34,0,HV Patel,Feroz Shah Kotla,Kumar Dharmasena,Vineet Kulkarni,O Nandan
690,7948,2018,Delhi,20/05/18,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,bat,normal,0,Delhi Daredevils,11,0,A Mishra,Feroz Shah Kotla,Kumar Dharmasena,O Nandan,Vineet Kulkarni

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
729,11325,2019,Delhi,18/04/19,Mumbai Indians,Delhi Capitals,Mumbai Indians,bat,normal,0,Mumbai Indians,40,0,HH Pandya,Feroz Shah Kotla Ground,Nigel Llong,Bruce Oxenford,Anil Chaudhary

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
698,11139,2019,Mumbai,24/03/19,Delhi Capitals,Mumbai Indians,Mumbai Indians,field,normal,0,Delhi Capitals,37,0,RR Pant,Wankhede Stadium,S Ravi,Yeshwant Barde,O Nandan